name: adhd_writing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  circular_timer: ^1.0.4
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  linear_progress_bar: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
